---
title: "Experimentación"
author: "Ronald"
output: pdf_document
---

# Feature extraction via computer vision
* This introductory paragraph describes the experimentation that is goin to be carried out to determine if current motion
caputre libraries are capable to extract quality data to build descriptors for activity and emotions clasifiers

## Motion capture libraries
* Preselección de librerias
* This paragraph mention selected libraries and its main features
* The second paragrahp introduces a table which list the quantity of points detectect for each library
* The second paragrahp list additional features of interest of the selected libraries


## Expermentation and benchmarking
* This paragraph introduces the experimentation goal and experiment methodology.
* This paragraph introduces the assesments criteria 
* This paragraph lists features of the selected video frames

Parrafo para mencionar las actividades que se van a incluir en el experimento
Activities
* Eating and smoking habits
* Aggresive conduct
* Recurrent extensions of work shift or activities

Parrafo para mencionar las emociones que se van a incluir en el experimento
* Stress-related emotions
* Anxiety-related emotions
* Depresion-related emotions

# Results

* This paragraph summarizes the obtained results by showing charts

## Activities results analysis
* Eating and smoking habits
* Aggresive conduct
* Recurrent extensions of work shift or activities

Parrafo de conclusiones de resultados


## Emotions results analysis
* Stress-related emotions
* Anxiety-related emotions
* Depresion-related emotions

Parrafo de conclusiones de resultados