# Generated by Django 3.0.3 on 2020-08-01 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataAsset',
            fields=[
                ('code', models.CharField(help_text='<strong>Identifier for the data asset.</strong>', max_length=256, primary_key=True, serialize=False, unique=True)),
                ('context', models.CharField(help_text='<strong>Description of the data asset context.</strong>', max_length=200)),
                ('registry_date', models.DateTimeField(help_text='<strong>Data asset registry date.</strong>', null=True)),
                ('data_mining_task', models.CharField(help_text='<strong>The expected data mining task to execute with the data asset.</strong>', max_length=20)),
                ('input_variables', models.CharField(blank=True, help_text='<strong>Input variables names.</strong>', max_length=4000, null=True)),
                ('input_variables_data_types', models.CharField(blank=True, help_text='<strong>Input variables data types.</strong>', max_length=4000, null=True)),
                ('response_variables', models.CharField(blank=True, help_text='<strong>Variables names containing the values the model is going to predict or classify.</strong>', max_length=500, null=True)),
                ('response_variables_data_types', models.CharField(blank=True, help_text='<strong>Response variables data types.</strong>', max_length=4000, null=True)),
                ('number_of_classes', models.IntegerField(help_text='<strong>Number of classes to predict (Only for classification tasks).</strong>', null=True, validators=[django.core.validators.MinValueValidator(2)])),
                ('raw_data', models.TextField(help_text='<strong>Raw data for further data mining task execution</strong>', null=True)),
            ],
            options={
                'db_table': 'dr_data_asset',
            },
        ),
    ]
