# Generated by Django 3.0.3 on 2020-08-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataasset',
            name='number_of_classes',
            field=models.IntegerField(default=0, help_text='<strong>Number of classes to predict (Only for classification tasks).</strong>', null=True),
        ),
    ]
