# Generated by Django 3.0.3 on 2020-08-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_registry', '0002_auto_20200803_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataasset',
            name='response_variables_data_types',
        ),
        migrations.AddField(
            model_name='dataasset',
            name='response_variables_data_type',
            field=models.CharField(blank=True, help_text='<strong>Response variables data types.</strong>', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dataasset',
            name='input_variables',
            field=models.TextField(help_text='<strong>Input variables names.</strong>', null=True),
        ),
        migrations.AlterField(
            model_name='dataasset',
            name='input_variables_data_types',
            field=models.TextField(help_text='<strong>Input variables data types.</strong>', null=True),
        ),
        migrations.AlterField(
            model_name='dataasset',
            name='response_variables',
            field=models.TextField(help_text='<strong>Variables names containing the values the model is going to predict or classify.</strong>', null=True),
        ),
    ]
