# Generated by Django 3.0.3 on 2020-08-03 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_registry', '0003_auto_20200803_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataasset',
            name='response_variables',
        ),
        migrations.RemoveField(
            model_name='dataasset',
            name='response_variables_data_type',
        ),
        migrations.AddField(
            model_name='dataasset',
            name='response_variable',
            field=models.CharField(help_text='<strong>Variables names containing the values the model is going to predict or classify.</strong>', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='response_variable_data_type',
            field=models.CharField(blank=True, help_text='<strong>Response variables data type.</strong>', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dataasset',
            name='data_mining_task',
            field=models.CharField(choices=[('REGRESSION', 'REGRESSION'), ('CLASSIFICATION', 'CLASSIFICATION')], help_text='<strong>The expected data mining task to execute with the data asset.</strong>', max_length=20),
        ),
        migrations.AlterField(
            model_name='dataasset',
            name='registry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 22, 56, 18, 739927), help_text='<strong>Data asset registry date.</strong>', null=True),
        ),
    ]
