# Generated by Django 3.0.3 on 2020-08-05 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_registry', '0004_auto_20200803_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataasset',
            name='registry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='<strong>Data asset registry date.</strong>', null=True),
        ),
    ]
