# Generated by Django 3.0.3 on 2020-08-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_registry', '0005_auto_20200805_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataasset',
            name='is_a_time_series_based_dataset',
            field=models.BooleanField(default=False, help_text='<strong>Determina si es un conjunto de datos corresponde a una serie temporal o si contiene un campo de fecha el cual sea relevante en la tarea de minería.</strong>'),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='main_date_field_name',
            field=models.CharField(help_text='<strong>Si la variable is_a_time_series_based_dataset es afirmativa, aquí deberá especificar el nombre del campo correspondiente a la fecha y que será empleadopara la integración con el calendario .</strong>', max_length=24, null=True),
        ),
    ]
