# Generated by Django 3.0.3 on 2020-08-06 00:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanDataAsset',
            fields=[
                ('code', models.CharField(help_text='<strong>Identificador de activo de datos.</strong>', max_length=256, primary_key=True, serialize=False, unique=True)),
                ('context', models.CharField(help_text='<strong>Descripción del contexto del activo de datos.</strong>', max_length=200)),
                ('registry_date', models.DateTimeField(default=django.utils.timezone.now, help_text='<strong>Fecha inicial de registro del activo de datos.</strong>', null=True)),
                ('updated_on', models.DateTimeField(help_text='<strong>Fecha de última actualización de datos.</strong>', null=True)),
                ('data_mining_task', models.CharField(choices=[('REGRESSION', 'REGRESSION'), ('CLASSIFICATION', 'CLASSIFICATION')], help_text='<strong>La tarea de minería de datos definida para el activo de datos.</strong>', max_length=20)),
                ('input_variables', models.TextField(help_text='<strong>Variables de entrada.</strong>', null=True)),
                ('input_variables_data_types', models.TextField(help_text='<strong>Tipos de datos de variables de entrada.</strong>', null=True)),
                ('response_variable', models.CharField(help_text='<strong>Nombre de la variable objetivo o de respuesta.</strong>', max_length=24, null=True)),
                ('response_variable_data_type', models.CharField(blank=True, help_text='<strong>Tipo de datos de la variable objetivo ode respuesta.</strong>', max_length=10, null=True)),
                ('number_of_classes', models.IntegerField(default=0, help_text='<strong>Número de clases a predecir (Sólo para tareas de clasificación).</strong>', null=True)),
                ('clean_data', models.TextField(help_text='<strong>Datos limpios para la generación de modelos</strong>', null=True)),
            ],
            options={
                'db_table': 'dp_clean_data_asset',
            },
        ),
        migrations.CreateModel(
            name='DataAssetPreprocessReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, default='', help_text='<strong>Identificador de activo de datos.</strong>', max_length=256)),
                ('preprocess_request_date', models.DateTimeField(default=django.utils.timezone.now, help_text='<strong>Fecha y hora en que se solicitó el preprocesamiento del activo de datos.</strong>')),
                ('preprocess_fulfillment_date', models.DateTimeField(help_text='<strong>Fecha y hora en que culminó el preprocesamiento de datos.</strong>', null=True)),
                ('preprocess_status', models.CharField(default='TO_PROCESS', help_text='<strong>Estado de procesamiento para el activo de datos management creation status.</strong>', max_length=10)),
                ('inputs_transformations', models.TextField(help_text='<strong>Transformaciones para cada variable de entrada</strong>', null=True)),
                ('inputs_pipeline', models.BinaryField(help_text='<strong>Binario del archivo de preprocesamiento que incluye las transformaciones implementadas para las variables de entrada</strong>')),
                ('response_transformations', models.TextField(help_text='<strong>Nombre de transformaciones para la variable objetivo o de respuesta.</strong>', null=True)),
                ('response_pipeline', models.BinaryField(help_text='<strong>Binario del archivo de preprocesamiento que incluye las transformaciones implementadas para la variable de salida</strong>')),
                ('includes_calendar_features', models.BooleanField(default=False, help_text='<strong>Determina si el activo de datos incluye variables derivadas de fecha.</strong>')),
                ('calendar_related_feature_names', models.TextField(help_text='<strong>Datos generados a partir de la fecha</strong>', null=True)),
                ('clean_data_start_date', models.DateField(help_text='<strong>Fecha inicial de registros dentro del activo de datos.</strong>', null=True)),
                ('dataset_end_date', models.DateField(help_text='<strong>Fecha final de registros dentro del activo de datos.</strong>', null=True)),
                ('is_the_current_data_preprocess', models.BooleanField(default=False, help_text='<strong>Indica si es manifiesto de procesamiento actual y a utilizar para tareas consecuentes</strong>')),
            ],
            options={
                'db_table': 'dp_data_asset_preprocess_report',
            },
        ),
        migrations.CreateModel(
            name='DataStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='<strong>Identificador de activo de datos</strong>', max_length=256, null=True)),
                ('statistics', models.TextField(help_text='<strong>Estadísticas en formato json</strong>', null=True)),
                ('data_asset_preprocess_id', models.ForeignKey(default=uuid.uuid4, help_text='<strong>Llave de relación con el reporte de preproceso</strong>', on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='data_preprocess.DataAssetPreprocessReport')),
            ],
            options={
                'db_table': 'dp_data_statistics',
            },
        ),
    ]
