# Generated by Django 3.0.3 on 2020-08-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_preprocess', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataassetpreprocessreport',
            old_name='includes_calendar_features',
            new_name='includes_calendar_features_integration',
        ),
    ]
