# Generated by Django 3.0.3 on 2020-08-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_preprocess', '0002_auto_20200806_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastatistics',
            old_name='data_asset_preprocess_id',
            new_name='data_asset_preprocess',
        ),
    ]
