# Generated by Django 3.0.3 on 2020-08-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_preprocess', '0003_auto_20200806_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleandataasset',
            old_name='clean_data',
            new_name='input_clean_data',
        ),
        migrations.RemoveField(
            model_name='cleandataasset',
            name='input_variables_data_types',
        ),
        migrations.RemoveField(
            model_name='cleandataasset',
            name='response_variable_data_type',
        ),
        migrations.RemoveField(
            model_name='dataassetpreprocessreport',
            name='calendar_related_feature_names',
        ),
        migrations.RemoveField(
            model_name='dataassetpreprocessreport',
            name='clean_data_start_date',
        ),
        migrations.RemoveField(
            model_name='dataassetpreprocessreport',
            name='dataset_end_date',
        ),
        migrations.RemoveField(
            model_name='dataassetpreprocessreport',
            name='includes_calendar_features_integration',
        ),
    ]
