# Generated by Django 3.0.3 on 2020-08-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_preprocess', '0004_auto_20200810_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleandataasset',
            old_name='input_clean_data',
            new_name='clean_data',
        ),
    ]
