---
title: "Propuesta"
author: "Ronald Fernando Rodríguez Barbosa^[Pontificia Universidad Javeriana, rfernandorodriguez@javeriana.edu.co]"
date: "Marzo 27 de 2020"
output:
  word_document: default
header-includes:
- \usepackage[spanish]{babel}
- \selectlanguage{spanish}
- \usepackage[utf8]{inputenc}
- \floatplacement{figure}{H}
#link-citations: yes
csl: ieee.csl
subtitle: Prueba
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problema de investigación

Existen situaciones en el entorno, que pueden influir sobre la salud de las personas. A estas situaciones, se les conoce como factores de riesgo y son definidas como cualquier rasgo, característica o exposición de un individuo que aumente su probabilidad de sufrir una enfermedad o lesión[@OMS2020], según la Organización Mundial de la Salud. Dentro del contexto mencionado, se pueden encontrar factores de riesgo de tipo químico[@LANDBERG2009]; factores de riesgo de tipo biológico [@CORRAO2012]; factores de riesgo ambiental [@MARSHALL2016] y factores de riesgo de tipo psicosocial (FRP). Los FRP involucran aspectos físicos del entorno como el ruido, la iluminación o la temperatura del entorno [@NATALETTI2008][@MIRZA2018] y aspectos psicológicos en las personas como el estrés[@CALDERON2019] y la fatiga laboral causada por la carga de trabajo o el exceso de horas trabajadas [@FORASTIERI2013][@PEDDITZI2014]. La motivación principal del presente proyecto, se centrará en los aspectos psicológicos y actividades relacionadas con los FRP. 

Dentro del contexto de los FRP,  existen investigaciones en las que se demuestra que algunas condiciones, generan efectos relacionados con la salud física como los desórdenes musculo esqueléticos [@ANDERSON1997] o la conducta de las personas como el sedentarismo [@MORALES2014]. Por otra parte, existen otros estudios que evidencian efectos relacionados con la salud mental como el estrés [@AZUMA2015] y trastornos psicológicos como la ansiedad [@WIEGNER2015] o la depresión [@LUCA2014]. En Colombia, el Ministerio de Salud reportó un total de 9.653 casos de enfermedades de naturaleza laboral durante el 2017, manifestados en diferentes actividades económicas como: comercio, hoteles, restaurantes, servicios domésticos, entre otros [@MINSALUD2018]. En el 2018, se registró un total de 155.167 casos de atención por riesgos potenciales para la salud, relacionados con circunstancias socioeconómicas y psicosociales, de los cuales 31.557 ocurrieron en la ciudad de Bogotá. Esta problemática crece año a año, según las estadísticas del Observatorio Nacional de Salud Mental [@MINSALUD2019]. 

En la actualidad, existen métodos que facilitan la evaluación de FRPO y que se han desarrollado a partir de la integración de modelos, que explican los mecanismos de generación de estrés asociados al trabajo. Blach, Sahagun y Cervantes, exponen un trabajo en el que consolidan los principales cuestionarios para la evaluación de FRP [@CHARRIA2011]. Otros trabajos como el de Abdullah Alotaibi[@ABDULLAH2020] y el de Christian Hederich [@HEDERICH2016] abordan la relación entre la calidad de sueño, el estres y el rendimiento académico. Sin embargo, estos procedimientos son susceptibles a la variabilidad e incluso subjetividad en las medidas [@CAICOYA2004], ya que la evaluación de los estudios no sólo se hace con una población reducida, sino que se efectua mediante el uso cuestionarios relacionados a aspectos y/o actividades diarias, que no son observados directamente por los especialistas en Seguridad y Salud en el Trabajo (SST), sino que son referidos por los trabajadores [@BENAVIDES2002].

Existen referentes que han abordado algunos aspectos relacionados con la salud mental de las personas[@CHOI2018][@GOLONKA2019]. Algunos de estos trabajos, han dado como resultado, soluciones tecnológicas para el monitoreo de algunos aspectos específicos de los FRP que van desde la implementación de controles de carga en las extremidades y otras partes del cuerpo a partir de sensores [@YONG2012], hasta la evaluación de estrés en personas, empleando imágenes de electroencefalograma [@JEBELLI2018]. Trabajos como los de Zack Zhu [@ZHU2016] o Raffaele Gravina [@GRAVINA2019], sugieren perspectivas alternativas, basadas en el reconocimiento de estado de ánimo, a partir de la captura de señales con dispositivos electrónicos portátiles. Si bien estos avances representan un gran potencial para la industria de manufactura, la construcción, entre otros [@REID2017], existen estudios como el de Shall Mark [@SCHALL2018], en el que se manifiestan como limitaciones para su adopción, las implicaciones de costo; la interrupción de las actividades laborales, el carácter intrusivo representado en  la incomodidad con los dispositivos y la privacidad de las personas. 

Otras aproximaciones, abordan la captura e integración con otras fuentes de datos, dando como resultado arquitecturas multimodales [@MAGDIN2016][@SOLEYMANI2017], en los que se aprovecha el procesamiento de imágenes de video, texto, señales, entre otros, para soportar el diagnóstico de emociones [@HARLEY2015]. Trabajos como el de Le Yang [@YANG2017] y Poria Soujana [@PORIA2017] sugieren la fusión de análisis de la paralingüística, la captura de respuesta de entrevistas, características del rostro que ha sido abordada ampliamente [@CAMPOS2016][@JAIN2018][@DINGES2005][@ZHU2018], y el movimiento de los ojos [@ALGHOWINEM2018]. En estas aproximaciones, se evidencia un aporte significativo en el análisis de patrones de voz, y se abordan algunos aspectos de interés dentro de la evaluación de FRP. Sin embargo, el modo de video utilizado en las publicaciones mencionadas, se enfocan sólo en el reconocimiento facial, requiriendo la captura de primer plano del rostro de las personas y el uso de sensores, cuya implementación tiene algunas limitaciones como se mencionó anteriormente. Adicionalmente, no se incluyen mecanismos en el que se realice un monitoreo constante. 

Dado al abordaje que se la hado dado a los aspecto psicológicos con la falta de observación directa, la carencia de un seguimiento automático e inteligente y las limitaciones de índole intrusivo, surge la pregunta: ¿Cómo calcular indicadores a partir de la detección de emociones y actividades para el monitoreo y apoyo a la evaluación factores de riesgos psicosociales, mediante un seguimiento automático no intrusivo, utilizando técnicas de inteligencia artificial y visión por computadora?

Para calcular los indicadores, el presente proyecto se enfocará en el diseño de mecanismos para la observación de forma continua de un conjunto de emociones y actividades de una persona. Dichos mecanismos, extraerán regiones de interés y características espacio-temporales que están relacionadas con aspectos cuantificables. Estos último serán integrados para la conformación de una serie de indicadores relacionados con estados de ánimo y comportamiento, para asistir al monitoreo y evaluación de FRP. El reto tecnológico, está representado en tres aspectos principales: El primero, corresponde al procesamiento de imágenes provenientes de cámaras convencionales, que son susceptibles a limitaciones como la posición y los datos que pueden proporcionar. El segundo, implica el seguimiento continuo e inteligente para la extracción de características y el cálculo de indicadores relacionados con estado de ánimo y las actividades. El tercer aspecto, corresponde a la integración de la información mencionada anteriormente, para la conformación de indicadores para la asistencia en la evaluación e incluso la materialización de FRP.

Los aspectos del reto tecnológico, se abordarán mediante la investigación y complementación de mecanismos para el reconocimiento de personas, sus posturas, expresiones faciales y corporales [@SCHINDLER2008][@STEUNEBRINK2010]. Con estos mecanismos, se extraerán indicadores a partir de métricas como la cantidad de veces en las que se ha manifestado tristeza o enojo. Por otra parte, estará el cálculo de indicadores relacionados con actividades desarrolladas durante la jornada laboral. En este caso, se identificará si una persona ha permanecido por más tiempo del normal en las instalaciones, si ha adoptado una conducta sedentaria, o  si ha manifestado episodios constantes de insomnio. Para la concepción de emociones, actvidades e indicadores de interés, se tomará como referencia cuestionarios o instrumentos manuales como el inventario de Beck [@SMRC2012], la escala PHQ-8 [@SMRC2012], entre otros [@MORA1991], [@PEKRUN2011]. Para el aspecto de la captura y el procesamiento de bajo nivel de las imágenes, se emplearán herramientas existentes. Sin embargo, existen escenarios en el que para la captura y seguimiento continuo de una persona, se requerirá el procesamiento de múltiples características de la misma fuente. Adicionalmente, la persona puede ser identificada a través de una cámara en un momento determinado y posteriormente cambiar su posición y ser identificada por otra cámara. Este tipo de problemáticas, han sido abordadas mediante arquitecturas basadas en agentes [@ABELLO2018][@VALENCIA2015][@ALCALA2017] en las que se definen tareas para su solución especializada, concurrente mediante la definición de estrategias de cooperación. Estas arquitecturas, brindan otros atributos como la concepción modular y la escalabilidad para desarrollo de sistemas distribuidos [@MANFREDI2016][@MITROVIC2014], que son relevantes para el diseño de los mecanismos, dentro de este proyecto.

LOs casos de referencia seleccionado para este proyecto, son los factores de riesgo psicospcial, que pueden estar presentes en el entorno académico por parte de los estudiantes y laboral para el caso de los profesores y personal administrativo.   es la oficina del área de consultoría y transformación digital de la empresa Vector ITC Colombia. Este escenario tiene afinidad con la problemática propuesta y se cuenta con la colaboración de la empresa mediante la asesoría del área de Personas y Cultura que se encarga del bienestar físico y psicológico de los trabajadores; el acceso a las imágenes de video y la colaboración de las personas para la experimentación.


## Metodologia

### Descripcion general

### Fase 1
[@AVEC2019]


### Fase 2

En esta fase, se diseñará una arquitectura con la que realizará la captura no intrusiva de  imágenes de video, haciendo el uso las cámaras existentes en las instalaciones de oficina (cámaras web instaladas en los computadores y cámaras de seguridad). Las imágenes serán utilizadas para la identificación  de estado de ánimo y actividades de una persona durante el trascurso del día. La arquitectura tendrá en cuenta aspectos como condiciones del entorno, ubicación de las cámaras existentes, su resolución captura, y las condiciones en que las imágenes son almacenadas y pueden ser extraídas, cuidando la privacidad de las personas que no autoricen el tratamiento de datos personales. La fase 2 se desarrollará en dos partes que se describen a continuación:

En la primera parte, se conformará un documento con la definición de la captura de las características antropométricas de personas que interpretarán algunos escenarios simulados.  Con la colaboración y capacitación de personal del área de Personas y Cultura, se capturarán en video, escenarios en el que los trabajadores simulan o dramatizan emociones positivas, negativas y situaciones de estrés, ansiedad o depresión. Con ello, se realizará un etiquetado de los videos, demarcando la presencia de los aspectos mencionados para soportar la definición de los mecanismos de reconocimiento. Posteriormente, se desarrollará una parte de la metodología CRISP-DM [@ACHARYA2000], en la que se definirán los indicadores relacionados con trastornos psicológicos y la materialización de FRPO, con el apoyo Personas y Cultura. Utilizando algunas de las herramientas que se determinaron como potenciales en la fase 1. Con ello, se determinarán los procesos pertinentes para la limpieza, preparación y conformación de las bases de entrenamiento, validación y pruebas. En la etapa modelamiento bajo la misma metodología, se compararán los modelos y  algoritmos sugeridos por la literatura, para la clasificación de aspectos relevantes y los mecanismos con mejores resultados para un aprendizaje orientado al contexto de FRPO. Los modelos seleccionados, serán validados con las muestras extraídas inicialmente y se establecerá un registro detallado de los resultados y las características de los modelos utilizados. 

En la segunda parte, se efectuará el proceso de diseño, en el que definen los aspectos a tener en cuenta en  la captura de imágenes en tiempo real, su procesamiento; el reconocimiento de entidades y escenarios a través de los modelos definidos; la persistencia de características y la inferencia de condiciones a partir de las mismas. El diseño de la arquitectura estará basada en agentes, los cuales serán especializados en el reconocimiento de imágenes donde se encuentre una persona, sus estados de ánimo, actividades y el cálculo de indicadores relevantes. Un ejemplo de cooperación entre los agentes, será la sincronización del reconocimiento de las personas en el momento de que dejen de ser capturadas por una cámara y comiencen a ser capturadas por otras. De la misma forma, la sincronización y cooperación se efectuará entre la captura de cámaras de seguridad y la captura desde una cámara web con el fin de complementar datos de alta relevancia. Adicionalmente, se incorporarán agentes encargados de los aspectos de temporalidad para determinar acciones y posturas en periodos de tiempo prolongado y que se presente con frecuencia para el cálculo los indicadores. La metodología que se utilizará para la especificación de los objetivos mencionados; las habilidades específicas de los agentes; los recursos y la cooperación entre los agentes mencionados, será AOPOA [@GONZALEZ2006]. Finalmente se diseñarán los mecanismos de inferencia para determinar los cambios de estados de ánimo, pre-diagnosticar trastornos psicológicos y conjuntos de acciones que hagan parte de un comportamiento o hábito y que puedan ser relevantes para la identificación de condiciones laborales dentro del contexto de FRPO.

El proceso de diseño tendrá un desarrollo iterativo e incremental, en el que se realizará una validación constante de los mecanismos, indicadores, obteniendo una retroalimentación del personal del área de Personas y Cultura, respecto a los resultados obtenidos. Por lo tanto, teniendo en cuenta el nivel de profundización con el que se efectuarán las tareas, la fase 2 tendrá una duración de un semestre con las siguientes actividades y entregables:  

### Fase 3

Una vez definido el documento de diseño de arquitectura, sistema multi-agente y mecanismos de inteligencia artificial, se desarrollará la fase 3 y que estará compuesta de dos partes. En la primera parte, se ejecutará el proceso de implementación de la solución. El desarrollo se llevará a cabo, tomando como referencia la metodología ágil SCRUM [@SCHWABER2012], definiendo un back-log con las características o historias y evaluando la cantidad de puntos para cada actividad. Posteriormente, se conformarán los sprints, con el conjunto de historias correspondientes para la fase del proyecto. Posteriormente, se evaluará la capacidad de clasificación de la arquitectura, a partir de su porcentaje de precisión y tiempos de respuesta en cada uno de los siguientes aspectos: detección y clasificación de estados de ánimo; detección y clasificación de actividades y pertinencia de los indicadores relacionados con trastornos psicológicos y materialización de FRPO. Por su parte, la utilidad de la arquitectura será evaluada basándose factor de utilidad percibida del modelo de aceptación de tecnología TAM[@VENKATESH2008], durante la realización de trabajo de campo para la identificación y evaluación de consecuencias o daños de origen psicosocial. Se generará un cuestionario para efectuar la evaluación y se solicitará al personal de personas y Cultura que realice una calificación de la relevancia y pertinencia de los valores de los indicadores obtenidos por los mecanismos. Adicionalmente, darán un punto de vista cualitativo del nivel de impacto para la organización y en el proceso de evaluación de FRPO.

Para la selección de personas que serán monitoreadas de manera simulada (capturas de video con actuación de escenarios y definidas en el protocolo experimental) y no simulada (capturas de video sin actuación), se redactará un documento de autorización de tratamiento de datos, siguiendo las disposiciones generales de la ley 1581 de protección de datos personales, en el que especificará de manera explícita la forma de captura y tratamiento de los datos obtenidos a través de las imágenes de video. Las personas que estén de acuerdo en participar del proyecto, se les informará y firmarán una copia de dicho documento en que autorizan el tratamiento de sus datos para fines académicos. Las personas que no estén de acuerdo y no otorguen la autorización, serán excluidas de los experimentos y sus datos no serán tratados.

La implementación parcial, involucra la intervención del sistema centralizado de recepción de imágenes capturadas por las cámaras de video así como los dispositivos de almacenamiento (para el caso de las cámaras de vigilancia). Adicionalmente se determinará la forma en que las cámaras están conectadas, el formato y la calidad de los videos. Se realizarán dos sesiones de toma: la primera con aspectos controlados en los que captura varios entornos con la presencia de una persona reconocida previamente por los mecanismos. En la segunda sesión, se realizará el ejercicio en un escenario libre, en el que intervendrán nuevas personas previamente reconocidas, en diferentes entornos. Este ejercicio tendrá como fin, determinar el comportamiento de la arquitectura y determinar las limitaciones. El proceso de captura de ambas sesiones, tendrá una duración de 1 mes y se contará con la compañía del personal del área de Personas y Cultura. Finalmente, la arquitectura y los resultados del proyecto, se plasmarán en la redacción de un artículo científico, el cual será presentado en un llamado de trabajos de un congreso académico nacional o internacional.

Teniendo en cuenta la envergadura de la implementación y la profundización con el que se efectuarán las tareas, la fase 3 tendrá una duración de un semestre con las siguientes actividades y entregables:  











