# Generated by Django 3.0.3 on 2020-08-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('key', models.CharField(help_text='<strong>The name of the property.</strong>', max_length=150, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[(0, 'APP_ADMIN'), (1, 'DATA_REGISTRY'), (2, 'DATA_PREPROCESS'), (3, 'MODEL_TRAINER'), (4, 'PREDICTION_DISPATCHER')], default='APP_ADMIN', help_text='<strong>The type of the property.</strong>', max_length=25)),
                ('value', models.CharField(help_text='<strong>The value of the property.</strong>', max_length=2000)),
            ],
            options={
                'db_table': 'apps_administration_property',
            },
        ),
    ]
