# Generated by Django 3.0.3 on 2020-08-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[(0, 'APP_ADMIN'), (1, 'DATA_REGISTRY'), (2, 'DATA_PREPROCESS'), (3, 'MODEL_TRAINER'), (4, 'DATA_CALENDAR'), (5, 'PREDICTION_DISPATCHER')], default='APP_ADMIN', help_text='<strong>The type of the property.</strong>', max_length=25),
        ),
    ]
