# Generated by Django 3.0.3 on 2020-08-01 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='<strong>The  date in format YYYY-MM-DD.</strong>', max_length=10)),
                ('day', models.IntegerField(help_text='<strong>Day number of the month.</strong>', null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)])),
                ('month', models.IntegerField(help_text='<strong>Month number.</strong>', null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('year', models.IntegerField(help_text='<strong>Year number.</strong>', null=True, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1990)])),
                ('day_of_week', models.CharField(help_text='<strong>Day of week represented as number. 1 for Monday, 2 for Tuesday and so on.</strong>', max_length=1, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('day_of_week_nominal', models.CharField(help_text='<strong>Day of week in nominal form.</strong>', max_length=10, null=True)),
                ('day_of_year', models.IntegerField(help_text='<strong>Day number of the year</strong>', null=True, validators=[django.core.validators.MaxValueValidator(366), django.core.validators.MinValueValidator(1)])),
                ('holiday', models.BooleanField(help_text='<strong>Logical value that represents whethera day is holiday or not.</strong>', null=True)),
                ('coded_holiday', models.SmallIntegerField(help_text='<strong>Coded value that represents whethera day is holiday or not.</strong>', null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('labor_day', models.BooleanField(help_text='<strong>Logical value that represents whethera day is labor day or not. A labor day is considered as a day of the week different toweekends or holidays.</strong>', null=True)),
                ('coded_labor_day', models.SmallIntegerField(help_text='<strong>Coded value that represents whethera day is labor day or not. A labor day is considered as a day of the week different to weekends or holidays.</strong>', null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(help_text='<strong>Description of the holiday or celebration is considered for that day.</strong>', max_length=100)),
            ],
            options={
                'db_table': 'dc_calendar',
            },
        ),
    ]
