# Generated by Django 3.0.3 on 2020-08-01 01:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastModelRecord',
            fields=[
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_task_type', models.CharField(choices=[(0, 'REGRESSION'), (1, 'CLASSIFICATION')], help_text='<strong>Task type of the model.</strong>', max_length=20, null=True)),
                ('is_last_model', models.BooleanField(default=False, help_text='<strong>Tag to describe whether is the current model  .</strong>')),
                ('code', models.CharField(db_index=True, help_text='<strong>The point which the training task is associated with.</strong>', max_length=100, unique=True)),
                ('input_variables', models.CharField(blank=True, help_text='<strong>Input variables to build the model.</strong>', max_length=4000, null=True)),
                ('response_variable', models.CharField(blank=True, help_text='<strong>Variable or classes variables the model is going to predictor classify.</strong>', max_length=500, null=True)),
                ('is_rfe_model', models.BooleanField(default=False)),
                ('selected_rfe_input_variables', models.CharField(blank=True, help_text='<strong>Input variables selected by the rfe process.</strong>', max_length=4000, null=True)),
                ('model_status', models.CharField(choices=[(0, 'ACTIVE'), (1, 'IN_TRAINING'), (2, 'TO_TRAIN'), (3, 'TRAINED'), (4, 'DEPRECATED')], help_text='<strong>Description of the training status.</strong>', max_length=20, null=True)),
                ('model_type', models.CharField(choices=[(0, 'LINEAR'), (1, 'RANDOM_FOREST'), (2, 'SVM'), (3, 'XG_BOOST_TREE')], help_text='<strong>Model type.</strong>', max_length=100, null=True)),
                ('model_base', models.BinaryField(help_text='<strong>Model representation in Bytes.</strong>', null=True)),
                ('model_grid_search_params', models.TextField(help_text='<strong>Grid search hyperparameters.</strong>', null=True)),
                ('model_best_params', models.TextField(help_text='<strong>Metrics selected and suitable for the model.</strong>', null=True)),
                ('main_score', models.DecimalField(decimal_places=2, default=0.0, help_text='<strong>Model main metric used to compare it with other models.</strong>', max_digits=5)),
                ('metrics', models.TextField(help_text='<strong>Metrics selected and suitable for the model.</strong>', null=True)),
                ('training_request_datetime', models.DateTimeField(help_text='<strong>Datetime of the training request.</strong>', null=True)),
                ('training_start_datetime', models.DateTimeField(help_text='<strong>Datetime when the training starts.</strong>', null=True)),
                ('training_end_datetime', models.DateTimeField(help_text='<strong>Datetime when the training ends.</strong>', null=True)),
            ],
            options={
                'db_table': 'mt_forecast_model_record',
            },
        ),
        migrations.CreateModel(
            name='MTSession',
            fields=[
                ('code', models.CharField(db_index=True, help_text='<strong>The code which the model is going to be associated with.</strong>', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('clean_data', models.TextField(help_text='<strong>Clean data for further training and avoid additional request</strong>', null=True)),
            ],
            options={
                'db_table': 'mt_session',
            },
        ),
    ]
