# Generated by Django 3.0.3 on 2020-08-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_trainer', '0002_auto_20200801_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastmodelrecord',
            name='model_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('IN_TRAINING', 'IN_TRAINING'), ('TO_TRAIN', 'TO_TRAIN'), ('TRAINED', 'TRAINED'), ('DEPRECATED', 'DEPRECATED')], help_text='<strong>Description of the training status.</strong>', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='forecastmodelrecord',
            name='model_task_type',
            field=models.CharField(choices=[('REGRESSION', 'REGRESSION'), ('CLASSIFICATION', 'CLASSIFICATION')], help_text='<strong>Task type of the model.</strong>', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='forecastmodelrecord',
            name='model_type',
            field=models.CharField(choices=[('LINEAR', 'LINEAR'), ('RANDOM_FOREST', 'RANDOM_FOREST'), ('SVM', 'SVM'), ('XG_BOOST_TREE', 'XG_BOOST_TREE')], help_text='<strong>Model type.</strong>', max_length=100, null=True),
        ),
    ]
