---
title: "Introducción"
author: "Ronald"
output: pdf_document
---

# Introduction 

According to the World Health Organization, a risk factor is defined as any trait or exposure of an individual that could increase the probability of suffering any disease or injury[@WHO2020]. Among different types of risk factors that can influence health, there are chemical[@LANDBERG2009]; biological[@SCARSELLI2010]; environmental[@WOJIC2012] and psycho-social.  This last one, involves physical aspects of the environment, such as noise or temperature[@NATALETTI2008]; psychological aspects in people such as stress[@CALDERON2019] and burnout caused by high workloads or persistent excess in working hours[@FORASTIERI2013][@PEDDITZI2014].

Throughout the last fifty years, several psycho-social assessment methods have been created by medical and psychology professionals, to allow quantitative and qualitative evaluation of psychosocial risk exposure. A psycho-social assessment is an evaluation of mental, physical, and emotional health[]. Usually, it takes the form of a series of questions and screening tools, covering many aspects of a person’s life to get a picture of his or her mental state[]. With that information, professionals can draw recommendations about specific environmental issues or treatment plans[].

On the other hand, since the end of the eighties, artificial intelligence has been used for applications in (specify kind of industry) industry, aeronautics, autonomous driving. As it is evolving, it has allowed the manufacturing of many devices for producing and interpreting the text, recognize speech, and even generate entities such as eBay's virtual agents. Artificial intelligence sub-disciplines such as machine Learning provides algorithmic tools to analyze data, as well as to design, train, and deploy models into applications or processes. However, machine learning algorithms and other artificial intelligence approaches are still under research in other areas such as well-being and psycho-social evaluations. 

The main goal of the present project is to identify a potential contribution of artificial intelligence to psycho-social risk assessment, by performing a state-of-the-art review of evaluation methods and current technological approaches to support them. This project will present implicit scenarios from questionnaires, where some artificial intelligence disciplines such as computer vision and machine learning, can be applied to obtain additional information for better informed assessments.  

The present work is composed of seven sections, including the previous introduction. In section 2, we present the Psycho-social Risk Assessment (PRIA) advantages and limitations, as well as technological approaches that support some aspects of PRIA. In section 3, we show the problem statement by describing the keywords review about the gap between artificial intelligence and PRIA. Also, it states the motivation of the present work. Section 4 is devoted to the description of questionary items that have the potential of being measured by extracting data captured with surveillance cameras. Section 5 list a set of articles oriented to recognize activities and emotions via single and multi-mode systems. Therefore, it will show techniques and methodologic references for the design and implementation of architectures based on artificial intelligence. Section 6 presents a brief review of motion-capture libraries that can be a potential component for feature extraction. In section 7, experimentation of selected libraries will be shown, using public video databases. Finally, we conclude the presented material in Section 8.