---
title: "Extracción Actividades Emociones"
author: "Ronald"
output: pdf_document
---

# Implicit Activities and emotions in PRIF-EM

From the review of the works related to the measurement of physical and psychological aspects in work and academic settings, a potential opportunity is found, for the use of artificial intelligence as a support component in the psycho-social assessment. The questionnaires currently used for quantitative and qualitative assessment implicitly contain activities, emotions, moods, and situations that the person providing the test answers may experience. In this project, we will limit ourselves to extracting the functional activities that are to support the physical, social, and psychological well-being of a person and allows that person to function in society []. Additionally, they will extract the Instrumental Activity of Daily Living (IADL), which is defined as those activities that allow an individual to live independently in a community. according[]. On the other hand, the emotions within the items of the questionnaires will be extracted, taking as reference the study of emotions by Paul Ekman [].

## Methodology of extraction

analysis of the mechanisms used in the publications. There are different motivations for the use of the mechanisms. It was found validation in specific population segments [], methodological quantification support for experimental validation [], and adaptation of some of its items in a defined context[]. The motivation, in this case, will be to identify the questionnaires mentioned in articles that establish their focus on aspects related to psychosocial risks in the work and academic contexts. After this, there was an extraction of application domains that group different items or questions made to the evaluated people. Each item was decomposed in order to identify implicit the activities, emotions. Also, activities frequencies considerations were extracted as a complement in activity characterization. This whole process was conducted by taking  Melzer's work [@MELZER2019] as references, which deals with the recognition of emotions from body movements. This approach not only represents a methodological reference but also fits with the scope of the work for the identification and characterization of scenarios in which actions carried out by people are involved and can be captured by video cameras.

Within the selected references, we could establish a separation between our two contexts of interest. Although the workplace context contains a wide variety of contributions evidenced in new assessment mechanisms development and possible improvements could be identified over other publications[], there is a considerable number of situations that have brought the attention of experts in medicine and psychology in the academic environment[]. The aspects evaluated in the academic field do not differ entirely from those studied in the workplace. There are few variations in the place where they take place and the role that people perform in these contexts. For instance, during the execution of the role of the teaching,  psychosocial risk factors related to work could be present. Table 3 shows the mechanisms extracted from the selected articles.


| **Author** | **Assesment mechanism or scale** |
|:-:|:--------:|
| Alotaibi-2020[@Alotaibi2020] | Pittsburgh Sleep Quality Index (PSQI) <br/> Kessler Psychological Distress Scale (K10) |
| Calderon-2019[@Calderon2019] | Ryff Scales of Psychological Well-being |
| Thomas-2019[@Thomas2019] | Perceived Scale Test (PSS) The Three-Factor Eating Questionnaire |
| Ben Ami-2018[@Benami2018] | Survey of personal and social development |
| Moy-2014[@Moy2014] | Smoking-alcohol consumption and physical activities (IPAQ) The job content questionnaire (JCQ) Depression-anxiety and stress scale (DASS) |
| Conley-2013[@Conley2013] | Psychometric analysis and refinement of the Connor Davidson Resilience Scale (CD-RISC) The Dysfunctional Attitude Scale |

Table: Articles oriented to academic environments

Moreover, the selection of articles related to the work environment is made (see table 4).  An analysis is performed to each related evaluation mechanism in order to extract the components of the questionnaires. Also, the analysis will permit to identify scales that support qualification.

| **Author** | **Environment** | **Assesment mechanism or scale** |
|:-:|:------:|
| Golonka-2019[@Golonka2019] | Maslach Burnout Inventory General Survey (MBI-GS)-NEO Five-Factor Inventory-Beck's Depression Inventory |
| Maeda-2016[@Maeda2016] | International Neuropsychiatric Interview |
| Najder-2016[@Najder2015] | The Psychosocial Risk Scale (PRS) |
| Luca-2014[@Luca2014] | Beck Depression Inventory (BDI) |
| Charria-2012[@Charria2012] | Cuestionario Encuesta de Calidad de Vida en el trabajo Cuestionario para la Evaluación del Estrés-Batería para la evaluación de factores de riesgo psicosocial Utrecht Work Engagement Scale Cuestionario Psicosocial de Copenhague (CoPsoQ) |
| Blanch-2010[@Blanch2010] | El cuestionario FPSICO El Cuestionario de Bienestar Laboral General |
| Rodríguez-2009[@Rodriguez2009] | Hipótesis de la tensión del trabajo Karasek |
| Boyes-2002[@Boyes2002] | Hospital Anxiety and Depression Scale-Short-form Supportive Care Needs Survey |
| Mausner-2000[@Mausner2000] | Quality of Employment Surveys |

Table: Articles oriented to Work environments 

The analysis process includes the understanding of the scope covered by the mechanism. One of the primary references in this work is the battery of psychosocial risk factor evaluation [] which takes up elements from the Karasek, Theorell (1990) and Jonhson models of demand-control-social support, from the imbalance model effort-reward of Siegrist (1996 and 2008) and of the dynamic model of the psychosocial risk factors of Villalobos (2005). The disposition of this evaluation mechanism suggests a construct of intra-labor conditions, which is made up of domains and dimensions. The domain of work demands includes the dimensions of quantitative demands, mental load, emotional, workday, environmental and physical effort. The control domain quantifies the dimensions related to autonomy overwork, clarity of the role, opportunities for development, the use of skills and abilities. The domain of leadership and control includes dimensions of characteristics of social relations at work, performance feedback, and the relationship with subordinates. Finally, the reward domain that includes the dimensions of recognition, compensation, and rewards derived from belonging to the organization, and the work is done.

On the other hand, the battery evaluates extra-labor conditions, which include aspects of the worker's family, social, and economic environment. In turn, they cover the conditions of the place of residence, which can influence the health and well-being of the individual. Time away from work, family relationships, communication, and interpersonal relationships, the financial situation of the family group, among others. The individual's conditions refer to a series of characteristics characteristic of each worker or socio-demographic characteristics such as sex, age, marital status, educational level, occupation (profession or trade), city or place of residence, scale socio-economic (socio-economic stratum), the type of dwelling and the number of dependents. These socio-demographic characteristics can modulate the perception and effect of intra-occupational and extra-occupational risk factors. They could be used as a complement to the characteristics used in classification or regression models to contribute to the support metrics for psychosocial assessment. Although the interest of this work focuses on the features related to activities and emotions, the mentioned scenarios will be extracted in the ongoing review of the different questionnaires.

## Activities and emotions inventory

In addition to identifying the scope, we proceed to identify the items or questions that may implicitly contain any activity or emotion experienced by the person evaluated. Table \ref{tab: activities} describes the evaluation mechanisms and a total of seventy-nine potential items. For each item, we identify what type of emotion or activity it could belong to as well as the related context. As can be seen, the Perceived Scale Test (PSS) questionnaire contains questions related to emotions as well as the frequency in which the evaluated person experiences these situations. These types of questions suggest a type of periodic control that could be used for the generation of a monthly indicator.

```{r activities, eval=T, echo=FALSE, message=F, warning=F}
library(dplyr)
library(kableExtra)
base_completa<-read.csv("../8_datasets_n_images/question.csv",sep =";",header=TRUE)
base_completa<-base_completa %>% mutate_if(is.numeric, format, digits=3,nsmall = 0)
base_completa<-base_completa[,c(1,8,6,7)]
kableExtra::kable(base_completa, caption="Items from questioneirs",format='latex',
                  booktabs = TRUE)%>%
      kable_styling(bootstrap_options = "striped", 
      font_size = 8,full_width = F,latex_options = "scale_down")  %>% pack_rows(
  index = c("Perceived Scale Test (PSS)" = 4, 
            "Depression, anxiety and stress scale (DASS21)" = 7, 
            "The Three-Factor Eating Questionnaire" = 4,
            "The Kessler Psychological Distress Scale (K10)" = 6, 
            "The Pittsburgh Sleep Quality Index (PSQI)" = 1, 
            "Survey of personal a social development" = 9, 
            "Maslach Burnout Inventory" = 2,
            "Occupational burnout scale" = 11,
            "Stress Assessment Questionnaire" = 10,
            "Cuestionario psicosocial de Copenhague" = 5,
            "Inventario de depresión de Beck" = 20)
)
```

Meanwhile, the Depression, anxiety, and stress scale (DASS21) manifest some activities that are noticeable such as body tremors or breathing difficulties. This representation of physical symptoms may be related to moods or medical conditions that are of interest for monitoring. Other activities that can be captured are those mentioned in The Three-Factor Eating Questionnaire. In this mechanism, activities are not only related to eating habits but also suggests a condition of anxiety in cases of a high frequency of food intake.

Like the PSS test, the Kessler Psychological Distress Scale (K10) includes items that inquire about emotional states over a while, being this a little more diverse in situations that suggest emotions and including drowsiness, which is addressed by The Pittsburgh Sleep Quality Index (PSQI). The Survey of personal and social development is an assessment-oriented questionnaire in academic settings. It mainly concerns the relevant aspects of the daily life of students and their habits. Also, this mechanism relates activities such as aerobic exercise or cigarette or alcohol consumption. For this academic context, an adaptation of the Maslach Burnout Inventory was reviewed as well, as it focuses on the emotions of the teaching staff during their working day as their motivation.

Other types of physical or somatic representations are dealt with on the Occupational burnout scale. In this mechanism, activities are around the actions that a person can have when experiencing physical pain or discomfort. In addition to these activities, actions related to stress can be identified. The Stress Assessment Questionnaire lists sleep disorders, difficulty staying still, and consumption of alcoholic beverages or smoking. As we can see, the Copenhagen psycho-social questionnaire contains a set of activities that include interaction and social isolation. Finally, other mechanisms relate situations and activities to anxiety and depression, such as the Beck Anxiety Inventory [@SANZ2012] and the Beck Depression Inventory.



